[package]
name = "wordcloud"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.32"
clap = { version = "4.5.60", features = ["derive"] }
image = "0.25.9"
imageproc = "0.26.0"
rand = "0.10.0"
